/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    docs: Doc;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    docs: DocsSelect<false> | DocsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('zh' | 'en') | ('zh' | 'en')[];
  globals: {
    navigation: Navigation;
    settings: Setting;
    'portal-home': PortalHome;
    'portal-nav': PortalNav;
    'portal-footer': PortalFooter;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'portal-home': PortalHomeSelect<false> | PortalHomeSelect<true>;
    'portal-nav': PortalNavSelect<false> | PortalNavSelect<true>;
    'portal-footer': PortalFooterSelect<false> | PortalFooterSelect<true>;
  };
  locale: 'zh' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Accounts that can sign in to the admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images used in the docs. Byte-identical images are stored only once.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Shown when the image fails to load; also read by screen readers.
   */
  alt: string;
  /**
   * SHA-256 of the file contents, computed on upload to prevent storing the same image twice.
   */
  sha256?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Content is written in Markdown. The slug is the URL path (e.g. about/intro).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs".
 */
export interface Doc {
  id: number;
  /**
   * Shown at the top of the page and in the sidebar.
   */
  title: string;
  /**
   * URL path such as about/intro (no language prefix). Generated from the title if left empty.
   */
  slug: string;
  /**
   * Used in search results and SEO metadata.
   */
  excerpt?: string | null;
  /**
   * Markdown source. Supports GFM, code blocks (Shiki highlighting) and automatic heading anchors.
   */
  content?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'docs';
        value: number | Doc;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sha256?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs_select".
 */
export interface DocsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Each group is a collapsible heading in the sidebar with documents under it.
   */
  groups?:
    | {
        label: string;
        collapsed?: boolean | null;
        items?:
          | {
              doc?: (number | null) | Doc;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Shown next to the logo and in the browser tab title.
   */
  siteName: string;
  /**
   * One or two characters shown in the logo square when no logo image is uploaded.
   */
  logoMark?: string | null;
  /**
   * Replaces the letter square in the top-left corner. PNG/SVG around 32px tall works best.
   */
  logo?: (number | null) | Media;
  /**
   * Browser tab icon — a square .ico / .png / .svg.
   */
  favicon?: (number | null) | Media;
  /**
   * Used by search engines and link previews.
   */
  description?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-home".
 */
export interface PortalHome {
  id: number;
  hero?: {
    badge?: string | null;
    line1?: string | null;
    line2?: string | null;
    subtitle?: string | null;
    title?: string | null;
    cta_start?: string | null;
    cta_demo?: string | null;
    cta_explore?: string | null;
    cta_contact?: string | null;
  };
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  centers?: {
    title?: string | null;
    subtitle?: string | null;
    /**
     * The key determines the flattened prefix: access / sec / ops
     */
    items?:
      | {
          /**
           * For example access / sec / ops; not localized
           */
          key: string;
          tab?: string | null;
          label?: string | null;
          desc?: string | null;
          features?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  values?: {
    title?: string | null;
    subtitle?: string | null;
    items?:
      | {
          title: string;
          desc?: string | null;
          /**
           * Optional
           */
          desc_long?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  solutions?: {
    title?: string | null;
    subtitle?: string | null;
    items?:
      | {
          key: string;
          title?: string | null;
          scene?: string | null;
          solution?: string | null;
          centers?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  moreProducts?: {
    title?: string | null;
    subtitle?: string | null;
    items?:
      | {
          key: string;
          name?: string | null;
          desc?: string | null;
          status?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  quickStart?: {
    title?: string | null;
    subtitle?: string | null;
    steps?:
      | {
          title?: string | null;
          desc?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-nav".
 */
export interface PortalNav {
  id: number;
  home?: string | null;
  products?: string | null;
  pricing?: string | null;
  about?: string | null;
  contact?: string | null;
  login?: string | null;
  console?: string | null;
  more_products?: string | null;
  cloudrouter_hub?: string | null;
  stage_evaluate?: string | null;
  stage_access?: string | null;
  stage_govern?: string | null;
  stage_scenario?: string | null;
  stage_worker?: string | null;
  cloudrouter?: string | null;
  accesscenter?: string | null;
  seccenter?: string | null;
  opscenter?: string | null;
  modelarena?: string | null;
  chatportal?: string | null;
  skillhub?: string | null;
  devagent?: string | null;
  vulnhunter?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-footer".
 */
export interface PortalFooter {
  id: number;
  description?: string | null;
  products?: string | null;
  centers?: string | null;
  more?: string | null;
  company?: string | null;
  resources?: string | null;
  status?: string | null;
  docs?: string | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  groups?:
    | T
    | {
        label?: T;
        collapsed?: T;
        items?:
          | T
          | {
              doc?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  logoMark?: T;
  logo?: T;
  favicon?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-home_select".
 */
export interface PortalHomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        line1?: T;
        line2?: T;
        subtitle?: T;
        title?: T;
        cta_start?: T;
        cta_demo?: T;
        cta_explore?: T;
        cta_contact?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  centers?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              key?: T;
              tab?: T;
              label?: T;
              desc?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  values?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              title?: T;
              desc?: T;
              desc_long?: T;
              id?: T;
            };
      };
  solutions?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              key?: T;
              title?: T;
              scene?: T;
              solution?: T;
              centers?: T;
              id?: T;
            };
      };
  moreProducts?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              key?: T;
              name?: T;
              desc?: T;
              status?: T;
              id?: T;
            };
      };
  quickStart?:
    | T
    | {
        title?: T;
        subtitle?: T;
        steps?:
          | T
          | {
              title?: T;
              desc?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-nav_select".
 */
export interface PortalNavSelect<T extends boolean = true> {
  home?: T;
  products?: T;
  pricing?: T;
  about?: T;
  contact?: T;
  login?: T;
  console?: T;
  more_products?: T;
  cloudrouter_hub?: T;
  stage_evaluate?: T;
  stage_access?: T;
  stage_govern?: T;
  stage_scenario?: T;
  stage_worker?: T;
  cloudrouter?: T;
  accesscenter?: T;
  seccenter?: T;
  opscenter?: T;
  modelarena?: T;
  chatportal?: T;
  skillhub?: T;
  devagent?: T;
  vulnhunter?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-footer_select".
 */
export interface PortalFooterSelect<T extends boolean = true> {
  description?: T;
  products?: T;
  centers?: T;
  more?: T;
  company?: T;
  resources?: T;
  status?: T;
  docs?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}